# Railway configuration
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/chat/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PORT = "8000"
